name: Algorithm CD
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        run: mvn clean install -DskipTests && HEROKU_API_KEY=${{ secrets.HEROKU_API_TOKEN }} mvn clean heroku:deploy